KutuphaneCoresuz/Controllers/YazarController.cs
using KutuphaneCoresuz.Models.Context;
using KutuphaneCoresuz.Models.Data;
using KutuphaneCoresuz.Models.ModelforDB;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace KutuphaneCoresuz.Controllers
{
    public class YazarController : Controller
    {
        private KutuphaneContext db = new KutuphaneContext();
               
        [AllowAnonymous]

        public ActionResult IndexYazar()
        {
            List<Yazar> yazarlar = new List<Yazar>();
            yazarlar = db.Yazarlar.ToList();
            List<Yazar> gosterilecekler = new List<Yazar>();
            foreach (var item in yazarlar)
            {
                if(item.aktiflik==1)
                {
                    gosterilecekler.Add(new Yazar { ID = item.ID, aktiflik = 1, Isim = item.Isim, Soyisim = item.Soyisim, Yorum = item.Yorum });
                    
                }
            }
 
            return View(gosterilecekler);
        }
        //yazarad soyad getirecek
        [HttpPost]
        [AllowAnonymous]
        public JsonResult AdSoyad(int? id, string tip = "yazarAdGetir")
        {
            List<Yazar> yazarlarListesi = new List<Yazar>();
            yazarlarListesi = db.Yazarlar.ToList();
            List<SelectListItem> sonuc = new List<SelectListItem>();
            bool basariliMi = true;
            //string yazarlar = "";
            try
            {
                switch (tip)
                {
                    case "yazarAdGetir":
                        foreach (var ad in yazarlarListesi)
                        {
                            if(ad.aktiflik==1)
                            {
                                sonuc.Add(new SelectListItem
                                {
                                    Text = ad.Isim + " " + ad.Soyisim,
                                    Value = ad.ID.ToString()
                                });
                            }
                            

                        }

                        break;
                    //case "yazarSoyadGetir":

                    //    foreach (var soyad in db.Yazarlar.Where(y => y.ID ==id).ToList())

                    //    {
                    //        if (id != null)
                    //        {
                    //            sonuc.Add(new SelectListItem
                    //            {
                    //                Text = soyad.Soyisim,
                    //                Value = soyad.ID.ToString()
                    //            });
                    //        }


                    //    }
                    //break;
                    default:
                        break;
                }

            }

            catch (Exception)
            {
                basariliMi = false;
                sonuc = new List<SelectListItem>();
                sonuc.Add(new SelectListItem
                {
                    Text = "Bir hata oluştu!",
                    Value = "default"
                });

            }

            return Json(new { ok = basariliMi, text = sonuc });
        }


        [AllowAnonymous]
        public ActionResult CreateYazarAction()
        {
            if (HttpContext.Session["KullaniciAdi"].Equals("admin") == false)
            {
                return RedirectToAction("Login", "Security");
            }
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult CreateYazarAction(Yazar yazar)
        {
            var yazarVarMi = db.Yazarlar.Where(y => y.Isim == yazar.Isim && y.Soyisim == yazar.Soyisim && y.Yorum == yazar.Yorum).FirstOrDefault();
            if(yazarVarMi==null)
            {
                if (ModelState.IsValid)
                {
                    Yazar yeniYazar = new Yazar();
                    yeniYazar.Isim = yazar.Isim;
                    yeniYazar.Soyisim = yazar.Soyisim;
                    yeniYazar.Yorum = yazar.Yorum;
                    yeniYazar.aktiflik = 1;
                    
                    db.Yazarlar.Add(yeniYazar);
                    db.SaveChanges();
                    //    KitapYazarAddModel kitapYazarModel = new KitapYazarAddModel();
                    //    List<SelectListItem> adi = (from i in db.Yazarlar.ToList()
                    //                                select new SelectListItem
                    //                                {
                    //                                    Text = i.Isim,
                    //                                    Value = i.ID.ToString()

                    //                                }).ToList();
                    //    List<SelectListItem> soyadi = (from j in db.Yazarlar.ToList()
                    //                                   select new SelectListItem
                    //                                   {
                    //                                       Text = j.Soyisim,
                    //                                       Value = j.ID.ToString()
                    //                                   }).ToList();
                }
            }
            else
            {
                yazarVarMi.aktiflik = 1;
                yazarVarMi.Isim = yazar.Isim;
                yazarVarMi.Soyisim = yazar.Soyisim;
                yazarVarMi.Yorum = yazar.Yorum;
                db.Entry(yazarVarMi).State = EntityState.Modified;
                db.SaveChanges();

            }

            //ViewBag["yazareklendi"] = "Yazar Başarılı Bir Şekilde Eklendi";
            return View();
        }
        // GET: Yazars/Details/5


        [HttpPost]
        [AllowAnonymous]


        public JsonResult DetailsYazarJson(int? id, string isim)
        {

            bool basarliMi = true;
            string sonuc = "EditUye";
            List<Yazar> model = new List<Yazar>();
            try
            {
                if (HttpContext.Session["KullaniciAdi"] == null)

                {
                    sonuc = "Login";
                    return Json(new { ok = basarliMi, text = sonuc });
                }
                //sonuc = "EditUye";
                var yazarResult = db.Yazarlar.Where(u => u.ID == id).FirstOrDefault();

                if (yazarResult != null)
                {
                    sonuc = "detailsYazar";
                    model.Add(new Yazar() { ID = yazarResult.ID, Isim = yazarResult.Isim, Yorum = yazarResult.Yorum });
                    //return View(model);

                    return Json(new { ok = basarliMi, text = sonuc });

                }
                sonuc = "hata";
                return Json(new { ok = basarliMi, text = sonuc });

            }
            catch (Exception)
            {
                basarliMi = false;
                sonuc = "Başarısız İşlem";
                return Json(new { ok = basarliMi, text = sonuc });
                throw;
            }


        }

        [AllowAnonymous]
        public ActionResult DetailsYazar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yazar yazar = db.Yazarlar.Find(id);
            if (yazar == null)
            {
                return HttpNotFound();
            }
            return View(yazar);
        }

        // GET: Yazars/Create
        //[AllowAnonymous]

        //public ActionResult CreateYazar()
        //{
        //    return View();
        //}

        // POST: Yazars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]

        [AllowAnonymous]

        public JsonResult CreateYazar(KitapYazarAddModel yazar)
        {
            bool basariliMi = true;
            int code = 0;
            try
            {
                
                if (ModelState.IsValid)
                {
                    Yazar yeniYazar = new Yazar();
                    yeniYazar.Isim = yazar.YazarAdi;
                    yeniYazar.Soyisim = yazar.YazarSoyadi;
                    yeniYazar.Yorum = yazar.YazarYorum;
                    yeniYazar.aktiflik = 1;
                    db.Yazarlar.Add(yeniYazar);
                    db.SaveChanges();
                    KitapYazarAddModel kitapYazarModel = new KitapYazarAddModel();
                    List<SelectListItem> adi = (from i in db.Yazarlar.ToList()
                                                select new SelectListItem
                                                {
                                                    Text = i.Isim,
                                                    Value = i.ID.ToString()

                                                }).ToList();
                    List<SelectListItem> soyadi = (from j in db.Yazarlar.ToList()
                                                   select new SelectListItem
                                                   {
                                                       Text = j.Soyisim,
                                                       Value = j.ID.ToString()
                                                   }).ToList();
                    kitapYazarModel.YazarAdlari = adi;
                    kitapYazarModel.YazarSoyadlari = soyadi;
                    //ViewBag.adlar = adi;
                    //ViewBag.soyadlar = soyadi;

                    //model.Add(new KitapYazarAddModel() { YazarSoyadi = yazar.Soyisim });




                }
                code = 1; //CreateKitap

                return Json(new { ok = basariliMi, text = code });//CreateKitap sayfasına yönlendirecek code=1
            }


            catch (Exception)
            {
                basariliMi = false;
                code = 2;

KutuphaneCoresuz/Views/Security/KitapAra.cshtml
@model  List<KutuphaneCoresuz.Models.ModelforDB.KitapYazarAddModel>
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Context.Session["KullaniciAdi"].ToString() == "admin")
{
    @Html.Partial("~/Views/Shared/_HeaderAdmin.cshtml")
}
else
{
    @Html.Partial("~/Views/Shared/_HeaderUye.cshtml")
}


@if (TempData["kitaparayok"] != null)
{
    <script>
    alert('@Html.Raw(TempData["kitaparayok"])')
    </script>
}
@*<table class="table-responsive table-hover" >
    <tr>
        <td>*@
<div style="position:absolute; left:500px; top:100px;">

    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <button type="button" class="btn btn-outline-secondary btn-ara">Ara</button>
            <button type="button" class="btn btn-outline-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <div class="dropdown-menu">
                <div role="separator" class="dropdown-divider"></div>
                <button class="dropdown-item btn-kitapara" type="submit">Kitaba Göre Ara</button>
                <div role="separator" class="dropdown-divider"></div>
                <button class="dropdown-item btn-yazarara" href="#">Yazara Göre Ara</button>
            </div>
        </div>
        <input type="text" class="form-control" id="kitapSearch" style="width:500px;" placeholder="Aramak istediğiniz kelimeyi yazınız.">
    </div>
</div>


@*</td>
    </tr>
    <tr>
        <td>

        </td>
    </tr>
    <tr>*@
<br />
<br />
<br />
<br />


<div id="divPartialView">
    @Html.Partial("_GridKitapPartialView", Model)

</div>

@*</tr>
    </table>*@

@section Scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            var searchVal = $("#kitapSearch");
            $(".btn-ara").click(function () {

                alert("butona basıldı");
                //Console.Log(searchVal.val());
                alert(searchVal.val());
                $.ajax({
                    type: "post", // POST call
                    url: `/Security/YazarSearch`, // call search action method of Home controller
                    data: { searchString: searchVal.val() },
                    // pass the parameter to action method. Here searchString is parameter of Action method from controller.
                    dataType: 'html', // return html to render
                    success: function (htmlContent) {
                        debugger
                        $('#divPartialView').html(htmlContent);

                        // Render filter result to div where partial view is there. We can render div and partial view should be inside div.
                    },
                    error: function () {
                        alert("Hatalı dönüş");
                    }
                });//ajax sonu

            });


        });//buton sonu

    </script>

}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>

KutuphaneCoresuz/Views/Security/Login.cshtml
@model KutuphaneCoresuz.Models.Data.Uye
@{
    Layout = null;
}

<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/Content/bootstrap-grid.css" rel="stylesheet" />
<link href="~/Content/bootstrap-grid.min.css" rel="stylesheet" />
<link href="~/Content/bootstrap-reboot.css" rel="stylesheet" />
<link href="~/Content/bootstrap-reboot.min.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/Site.css" rel="stylesheet" />
<link href="~/Content/cssLogin.css" rel="stylesheet" />
@if (TempData["null"] != null)
{
    <script>
        alert('@Html.Raw(TempData["null"])');
    </script>
}
@if (TempData["LoginError"] != null)
{
    <script>
        alert('@Html.Raw(TempData["LoginError"])');
    </script>
}

<div class="container">
    <div class="row">
        <div class="col-lg-6 col-md-8 login-box">
            <div class="col-lg-12 login-key">
                <i class="carousel-fade" aria-hidden="true"></i>
                @*<p class="alert-danger">@ViewBag.Error</p>*@
            </div>

            <div class="col-lg-12 login-title">
                GİRİŞ EKRANI
            </div>
            <div>
                @ViewBag.LoginError
            </div>
            <div class="col-lg-12 login-form">
                <div class="col-lg-12 login-form">

                    @using (Html.BeginForm("Login", "Security", FormMethod.Post))
                    {
                        <div class="form-group">
                            @Html.Label("Kullanıcı Adı", "Kullanıcı Adı:", new { @class = "form-control-label" })

                            @Html.TextBoxFor(model => model.KullaniciAdi, "", new { placeholder = "Kullanıcı Adınız:", @class = "form-control" })
                        </div>
                        <div>
                            @Html.Label("Şifre:", "Sifreniz:", new { @class = "form-control-label" })
                            @Html.PasswordFor(model => model.Sifre, new { placeholder = "Şifreniz:", @class = "form-control" })
                        </div>
                        <div>
                            <div class="col-lg-6 login-btm login-button">
                                <br />
                                <button type="submit" class="btn-dark btn-outline-light" id="giris" name="kayit" style="width:100px; height:50px; position:page; ">Giriş Yap</button>
                                @if (TempData["loginbasarili"] != null)
                                {
                                    <script>
                                    alert('@Html.Raw(TempData["loginbasarili"])')
                                    </script>
                                }

                                @if (TempData["loginbasarisiz"] != null)
                                {
                                    <script>
                                    alert('@Html.Raw(TempData["loginbasarisiz"])')
                                    </script>
                                }


                                @if (TempData["kayitsiz"] != null)
                                {
                                    <script>
                                    alert('@Html.Raw(TempData["kayitsiz"])')
                                    </script>
                                }

                                @*<form>*@
                                <br />
                                <button type="button" onclick="location.href='@Url.Action("CreateUye","Uye")'" class="btn-dark btn-outline-light" style="width:100px; height:50px; position:page; " name="giris"> Kayıt Ol</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div> 
</div>

        @*<script type="text/javascript">
            $(document).ready(function() {
    console.log( "ready!" );
});*@
             @*$(document).ready(function() {
                 alert("sfsd");
                $("#giris").click(function () {
                     if ('@TempData["loginbasarili"]' != null) 
                    alert('@TempData["loginbasarili"]');

            if ('@TempData["loginbasarisiz"]' != null)
                    alert('@TempData["loginbasarisiz"]');

                  if ('@TempData["kayitsiz"]' != null)
                    alert('@TempData["kayitsiz"]');

                });

                
            });*@
  
        @*</script>*@



    

KutuphaneCoresuz/Views/Security/UyeAnasayfasi.cshtml
@model List<KutuphaneCoresuz.Models.ModelforDB.KitapYazarAddModel>


@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "anasayfa";

}

@Html.Partial("~/Views/Shared/_HeaderUye.cshtml")
@if (TempData["kitapyok"] != null)
{
    <script>
        alert('@Html.Raw(TempData["kitapyok"])')
    </script>
}


    <h4 style="font-family:fantasy; color:	#01579B; padding-left:20px">Projeye Hoşgeldiniz @Context.Session["KullaniciAdi"].ToString() </h4>

<h3 align="center">Var Olan Kitaplarınız</h3>

<table class="table" align="center" style="width:45%; height:200px" cellspacing="0" cellpadding="0">
    <thead>
        <tr>
            <th> @Html.Label("Kitap Adi:")</th>
            <th>
                @Html.Label("Yazar Adi:")

            </th>
            <th>
                @Html.Label("Yazar Soyadi:")

            </th>
            <th>
                @Html.Label("Yayinci:")
            </th>
            <th>
                @Html.Label("Yorum:")
            </th>
            <th>
                @Html.Label("Kitap Durum")
            </th>

        </tr>
    </thead>
    <tbody>

        @if (Model != null)
        {

            foreach (var item in Model)
            {

                <tr>
                    <td>
                        @item.KitapAdi
                    </td>
                    <td>
                        @item.YazarAdi
                    </td>
                    <td>
                        @item.YazarSoyadi
                    </td>
                    <td>
                        @item.yayinci
                    </td>
                    <td>
                        @item.Aciklama
                    </td>
                    <td>
                        @item.KitapDurum
                    </td>


                </tr>

            }

        }
    </tbody>
</table>

<br />
<br />




@section Scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            $(".btn-duzenle").click(function () {
                var id = $(this).data("id");
                //alert(id);
                var isim = $(this).data("isim");
               // alert(isim);
                var soyisim = $(this).data("soisim");

                var yorum = $(this).data("yorum");

                $.ajax({
                   url: `https://localhost:44339/Yazar/EditYazarId?id="${id}&isim=${isim}&soyisim=${soyisim}&yorum=${yorum}"`,
                    @*url:'@Url.Action("EditYazarId","Yazar")',*@
                    method: "post",
                    dataType: "json",
                   // data: {id:yazarID, isim:isim, soyisim:soyisim, yorum:yorum},
                    success: function (data) {

                    }, complete: function () {

                    }
                });
            })

        });

        $(document).ready(function () {
            $(".btn-sil").click(function () {
                var isim = $(this).data("isim");
                var soyisim = $(this).data("soisim");
                var yorum = $(this).data("yorum");
                $.ajax({
                    url: `https://localhost:44339/Yazar/DeleteYazar?isim="${isim}&soyisim=${soyisim}&yorum=${yorum}"`,
                    @*/  url:'@Url.Action("EditYazarId","Yazar")',*@
                    method: "post",
                    dataType: "json",
                   // data: {id:yazarID, isim:isim, soyisim:soyisim, yorum:yorum},
                    success: function (data) {

                    }, complete: function () {

                    }
                });
            })

        });

    </script>


}

KutuphaneCoresuz/Views/Security/UyeKitaplarSayfasi.cshtml
@{
    ViewBag.Title = "Menu";
    Layout = "~/Views/Shared/_Layout.cshtml";

}


<div id="header">
    <div class="container">

        <div id="logo" class="pull-left">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @*   bu satır küçük çaplı sadırılara karşı koruma sağlar *@
                <div class="form-horizontal">
                    <h4>Uye Sayfasi</h4>
                    <hr />


                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                </div>

            }
        </div>
    </div>
</div>
}

KutuphaneCoresuz/Views/Security/UyeSayfasi.cshtml
@{
    ViewBag.Title = "Menu";
    Layout = "~/Views/_Layout.cshtml";
}

@section Header{

    <div id="header">
        <div class="container">

            <div id="logo" class="pull-left">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @*   bu satır küçük çaplı sadırılara karşı koruma sağlar *@
                <div class="form-horizontal">
                    <h4>Uye Sayfasi</h4>
                    <hr />
                   

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                </div>

                }
            </div>
        </div>
    </div>
}