KutuphaneCoresuz/Controllers/KitapController.cs
using KutuphaneCoresuz.Models;
using KutuphaneCoresuz.Models.Context;
using KutuphaneCoresuz.Models.Data;
using KutuphaneCoresuz.Models.ModelforDB;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace KutuphaneCoresuz.Controllers
{
    public class KitapController : Controller
    {
        KutuphaneContext db = new KutuphaneContext();

        // GET: Kitap
        public ActionResult Index()
        {
            return View();
        }

        // GET: Kitaps
     
        [AllowAnonymous]
        public ActionResult IndexKitap()
        {
         
            if (HttpContext.Session["KullaniciAdi"] == null)
            {
                return RedirectToAction("Login","Security");
            }
            
            List<KitapYazarAddModel> model = new List<KitapYazarAddModel>();
            List<Kitap> kitap = new List<Kitap>();
            kitap = db.Kitaplar.ToList();
           // var kitaplar = db.Kitaplar.First();
            //var yazarResult = db.Yazarlar.First();
            if (kitap.Count()!= 0)
            {
                foreach (var item in kitap)
                {
                    if(item.aktiflik==1)
                    {
                        model.Add(new KitapYazarAddModel() { Id = item.ID, KitapAdi = item.Isim, Aciklama = item.Aciklama, yayinci = item.Yayinci, YazarAdi = item.Yazar.Isim, YazarSoyadi = item.Yazar.Soyisim });
                    }
                    
                }
                if (model != null)
                {
                    return View(model);
                }
            }
            else
            {
                TempData["kitapyok2"] = "Hiç Kİtap Yok";
            }


            return View();
        }


        [HttpPost]
        [AllowAnonymous]


        public JsonResult DetailsKitapJson(int? id, string isim)
        {

            bool basarliMi = true;
            string sonuc = "detailsKitap";
            List<Kitap> model = new List<Kitap>();
            try
            {
                if (HttpContext.Session["KullaniciAdi"] == null)

                {
                    sonuc = "Login";
                    return Json(new { ok = basarliMi, text = sonuc });
                }
                //sonuc = "EditUye";
                var kitapResult = db.Kitaplar.Where(u => u.ID == id).FirstOrDefault();

                if (kitapResult != null)
                {
                    sonuc = "detailsKitap";
                    model.Add(new Kitap() { ID = kitapResult.ID, Isim = kitapResult.Isim, Yayinci = kitapResult.Yayinci });
                    //return View(model);

                    return Json(new { ok = basarliMi, text = sonuc });

                }
                sonuc = "hata";
                return Json(new { ok = basarliMi, text = sonuc });

            }
            catch (Exception)
            {
                basarliMi = false;
                sonuc = "Başarısız İşlem";
                return Json(new { ok = basarliMi, text = sonuc });
                throw;
            }


        }
        // GET: Kitaps/Details/5
        [AllowAnonymous]
        public ActionResult DetailsKitap(KitapYazarAddModel model)
        {
            int id = 0;
            //modelin içinde kitap id var 
            
                id = model.Id;
                if (id == 0)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                // List<KitapYazarAddModel> gosterilecek = new List<KitapYazarAddModel>();
                //List<Kitap> kitaplar = db.Kitaplar.Where(k=>k.ID==id).ToList();


           
           


                if (model == null)
                {
                    return HttpNotFound();
                }
                return View(model);
            
        }
        [HttpPost]
        [AllowAnonymous]
        public JsonResult AdSoyad(int? id, string tip = "yazarAdGetir")
        {
            List<Yazar> yazarlarListesi = new List<Yazar>();
            yazarlarListesi = db.Yazarlar.ToList();
            List<SelectListItem> sonuc = new List<SelectListItem>();
            bool basariliMi = true;
            //string yazarlar = "";
            try
            {
                switch (tip)
                {
                    case "yazarAdGetir":
                        
                        foreach (var ad in yazarlarListesi)
                        {
                            if(ad.aktiflik==1)
                            {
                             sonuc.Add(new SelectListItem
                                         {
                                            Text = ad.Isim +" " +ad.Soyisim,
                                            Value = ad.ID.ToString()
                                          });                                                             

                            }                           
                           

                        }
                       
                        break;
                    //case "yazarSoyadGetir":
                       
                    //    foreach (var soyad in db.Yazarlar.Where(y => y.ID ==id).ToList())
                            
                    //    {
                    //        if (id != null)
                    //        {
                    //            sonuc.Add(new SelectListItem
                    //            {
                    //                Text = soyad.Soyisim,
                    //                Value = soyad.ID.ToString()
                    //            });
                    //        }


                    //    }
                        //break;
                    default:
                        break;
                }
               
            }
          
            catch (Exception) 
            {
                basariliMi = false;
                sonuc = new List<SelectListItem>();
                sonuc.Add(new SelectListItem
                {
                    Text = "Bir hata oluştu!",
                    Value = "default"
                });

            }

           return Json(new { ok = basariliMi, text = sonuc });
        }

  
        // GET: Kitaps/Create
        [AllowAnonymous]
        [OutputCache(CacheProfile = "anaSayfaCache")]
        public ActionResult CreateKitap()
        {
            //Yazar yazarlar = new Yazar();
            //// List<string> yazarlistesi = new List<string>();
            //List<SelectListItem> yazarIsimListesi = (from k in db.Yazarlar
            //                                         select new SelectListItem
            //                                         {
            //                                             Text = k.Isim

            //                                         }
            //    ).ToList();
            ////ViewBag.yazarlarlistesi = new SelectList(yazarlistesi, "Isim");
            //ViewBag.yazarlarIsimlistesi = yazarIsimListesi;

            //List<SelectListItem> yazarSoyisimListesi = (from k in db.Yazarlar
            //                                            select new SelectListItem
            //                                            {
            //                                                Text = k.Soyisim

            //                                            }
            //   ).ToList();
            ////ViewBag.yazarlarlistesi = new SelectList(yazarlistesi, "Isim");
            //ViewBag.yazarlarSoyisimlistesi = yazarSoyisimListesi;

            if (HttpContext.Session["KullaniciAdi"] == null)
            {
               
                return RedirectToAction("Login","Security");
            }


            return View();


            //var yazarlar = db.Yazarlar.Select(q => q.Isim).OrderBy(q => q);

            //foreach (var item in yazarlar)
            //{
            //    yazarlistesi.Add(item);
            //}

        }
        [OutputCache(CacheProfile = "anaSayfaCache")]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        [HttpPost]
        public ActionResult CreateKitap(KitapYazarAddModel model)
        {

            //dropdown doldurmak için
            KitapYazarAddModel kitapYazarAddModel = new KitapYazarAddModel();
            List<SelectListItem> modelAdList = new List<SelectListItem>();
            List<SelectListItem> modelSoyadList = new List<SelectListItem>();
            Kitap yeniKitap = new Kitap();
            UyeKitap yeniUyeKitap = new UyeKitap();
            int SeciliYazarID = Convert.ToInt32(model.YazarAdi);

            var SeciliKitapAdi = model.KitapAdi;
            string AktifUye = HttpContext.Session["KullaniciAdi"].ToString();
            var KitapVarmi = db.Kitaplar.Where(k => k.Isim == SeciliKitapAdi).FirstOrDefault();
            var YazarResult = db.Yazarlar.Where(i => i.ID == SeciliYazarID).FirstOrDefault();
            if (AktifUye.Equals("admin") == true)//admine kitap eklemesin admin sadece sisteme kitap eklesin diye
            {
                if (KitapVarmi == null)//yeni kitap gelmiş demektir
                {
                    if (SeciliYazarID != 0)//yazar seçmediniz hatası için
                    {
                        if (ModelState.IsValid)
                        {
                            //önce kitap tablosu
                            yeniKitap.Isim = model.KitapAdi;
                            yeniKitap.Yayinci = model.yayinci;
                            yeniKitap.Aciklama = model.Aciklama;
                            yeniKitap.YazarID = SeciliYazarID;
                            yeniKitap.Yazar = YazarResult;
                            yeniKitap.aktiflik = 1;
                            //sadece kitap ekleyecek
                            //Fk ve ilişili tablolara ekleme işlemi yapılmayacak aktifUye eğer adminse
                            db.Kitaplar.Add(yeniKitap);

KutuphaneCoresuz/Views/Shared/_GridKitapPartialView.cshtml
@model List<KutuphaneCoresuz.Models.ModelforDB.KitapYazarAddModel>
@{
    ViewBag.Title = "_GridKitapPartialView";
 
}



@{
    WebGrid webgrid = new WebGrid(source: Model, canPage: true, rowsPerPage: 10, canSort: true, selectionFieldName: "selectedRow", ajaxUpdateContainerId: "grid", fieldNamePrefix: "gridItem");
    webgrid.Pager(WebGridPagerModes.NextPrevious);

}
@*@using (Html.BeginForm("Arama", "Kitap", FormMethod.Post, new { @class = "form-inline md-form form-sm mt-0" }))
    {*@

@*<i class="fas fa-search" aria-hidden="true" style="position:absolute; right:5px; top:50px;"> Arama Yap</i>
    <input class="form-control form-control-sm ml-3 w-75" type="text" placeholder="Search"
           aria-label="Search"  style="position:absolute; right:5px; top:50px;">
    <button class="btn aqua-gradient btn-rounded btn-sm my-0" type="submit"  style="position:absolute; right:5px; top:70px;">Search</button>*@
@*<div style="position:absolute; right:5px; top:50px;">
        <form class="example" action="" style="margin:auto;max-width:300px ">
            <input type="text" placeholder="Search.." name="search2" id="txtSearch">
            <button type="submit"><i class="fa fa-search"></i></button>
        </form>

    </div>*@


@* } *@


    <div id="grid">
        @webgrid.GetHtml(
         columns:
                webgrid.Columns
                (webgrid.Column(null, null, format: @<input type="hidden" name="IDHidden" value="@item.ID" />),
webgrid.Column("KitapAdi", header: "Kitap Adı", format: @<text>@item.KitapAdi</text>, style: "NameColWidth"),
webgrid.Column("YazarAdi", header: "Yazar Adı", format: @<text>@item.YazarAdi</text>, style: "NameColWidth"),
webgrid.Column("YazarSoyadi", header: "Yazar Soyadı", format: @<text>@item.YazarSoyadi</text>, style: "NameColWidth"),
webgrid.Column("yayinci", header: "Yayıncı", format: @<text>@item.yayinci</text>, style: "NameColWidth"),
webgrid.Column("Aciklama", header: "Açıklama", format: @<text>@item.Aciklama</text>, style: "NameColWidth"),
webgrid.Column("YazarYorum", header: "Yazar Yorum", format: @<text>@item.YazarYorum</text>, style: "NameColWidth"),
webgrid.Column("KitapDurum", header: "Kitap Durum", format:@<text>@item.KitapDurum</text>),
webgrid.Column(null, null, format: @<input type="hidden" name="IDHidden" value="@item.ID" />)






),

tableStyle: "webgrid",
mode: WebGridPagerModes.All,
headerStyle: "webgrid-header",
footerStyle: "webgrid-footer",
selectedRowStyle: "webgrid-selected-row",
rowStyle: "webgrid-row-style")



    @*//htmlAttributes: new { @id = "webgrid" },
            //columns: webgrid.Columns(
            //    webgrid.Column("ID","Id"),
            //    webgrid.Column("KitapAdi", "Kitap Adi"),
            //     webgrid.Column("YazarAdi", "Yazar Adi"),
            //      webgrid.Column("Yazar Soyadi", "Yazar Soyadi"),
            //     webgrid.Column("Yayinci", "Yayinci"),
            //     webgrid.Column("Aciklama", "Aciklama"),
            //     webgrid.Column("Yazar Yorum", "Yazar Yorum"),
            //     webgrid.Column("Kitap Durum", "Kitap Durum")
                webgrid.Column("KitapAdi", header: "Kitap Adı", format: @<text>@item.KitapAdi</text>, style: "NameColWidth"),
    webgrid.Column("YazarAdi", header: "Yazar Adı", format: @<text>@item.YazarAdi</text>, style: "NameColWidth"),
    webgrid.Column("YazarSoyadi", header: "Yazar Soyadı", format: @<text>@item.YazarSoyadi</text>, style: "NameColWidth"),
    webgrid.Column("yayinci", header: "Yayıncı", format: @<text>@item.yayinci</text>, style: "NameColWidth"),
    webgrid.Column("Aciklama", header: "Açıklama", format: @<text>@item.Aciklama</text>, style: "NameColWidth"),
    webgrid.Column("YazarYorum", header: "Yazar Yorum", format: @<text>@item.YazarYorum</text>, style: "NameColWidth"),
    webgrid.Column("KitapDurum", header: "Kitap Durum", format:@<text>@item.KitapDurum</text>)


    *@




    </div>

KutuphaneCoresuz/Views/Shared/_HeaderAdmin.cshtml
<header id="header">
    <div class="container">

        <div id="logo" class="pull-left" style="position:absolute; top:5px; left:10px;">


            <span class="border-dark border-bottom">
                <h4 style="font-family:fantasy; color:	#01579B; padding-left:20px">Projeye Hoşgeldiniz @Context.Session["KullaniciAdi"].ToString() </h4>
            </span>
        </div>

        @*@if(ViewContext.RouteData.Values["controller"].ToString()=="UyeAnaSayfasi")
        {

        }*@

        <nav id="nav-menu-container">
            <ul class="nav-menu">
                <li>@Html.ActionLink("Anasayfa", "IndexAdmin", "Admin", new { area = "" }, new { @class = "navbar-brand" })</li>

                <li>@Html.ActionLink("Giriş Sayfası", "Login", "Security", new { area = "" }, new { @class = "navbar-brand" })</li>

                <li class="menu-has-children">
                    @*@Html.ActionLink("Keşfet", "Contact", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
                <li class="menu-has-children">
                    @Html.ActionLink("Ekle", "", "")
                    <ul>
                        <li><a href="#"></a></li>
                        <li><a href=@Url.Action("CreateYazarAction","Yazar")>Sisteme Yazar Ekle</a></li>
                        <li><a href="@Url.Action("CreateKitap","Kitap")">Sisteme Kitap Ekle</a></li>
                        <li><a href="@Url.Action("AddUyeAdmin","Admin")"> Sisteme Uye Ekle</a></li>
                        <li><a href="@Url.Action("IndexYazar","Yazar")">Tüm Yazarlar</a></li>
                        <li><a href="@Url.Action("IndexKitap","Kitap")">Tüm Kitaplar</a></li>

                    </ul>
                <li class="menu-has-children">
                    @Html.ActionLink("Sil", "", "")
                    <ul>
                        <li><a href="#"></a></li>
                        <li><a href=@Url.Action("IndexYazar","Yazar")> Sistemden Yazar Sil</a></li>
                        <li><a href="@Url.Action("IndexKitap","Kitap")">Sistemden Kitap Sil</a></li>
                        <li><a href="@Url.Action("AdminDeleteUyeResult","Admin")">Sistemden Uye Sil</a></li>
                        <li><a href="@Url.Action("IndexYazar","Yazar")">Tüm Yazarlar</a></li>
                        <li><a href="@Url.Action("IndexKitap","Kitap")">Tüm Kitaplar</a></li>

                    </ul>
                @*<li class="menu-has-children">
                    @Html.ActionLink("Sil", "", "")
                    <ul>
                        <li><a href="#"></a></li>
                        <li><a href=@Url.Action("IndexYazar","Yazar")> Sistemden Yazar Sil</a></li>
                        <li><a href="@Url.Action("IndexKitap","Kitap")">Sistemden Kitap Sil</a></li>
                        <li><a href="@Url.Action("AdminDeleteUyeResult","Admin")">Sistemden Uye Sil</a></li>
                        <li><a href="@Url.Action("IndexYazar","Yazar")">Tüm Yazarlar</a></li>
                        <li><a href="@Url.Action("IndexKitap","Kitap")">Tüm Kitaplar</a></li>

                    </ul>

                </li>*@
                <li class="menu-has-children">
                    @Html.ActionLink("Profil", "UyeAnaSayfasi", "Security")
                    <ul>
                        <li><a href="#"></a></li>
                        <li><a href=@Url.Action("DetailsUye","Uye")>Profil Görüntüle</a></li>
                        <li><a href="@Url.Action("EditUye","Uye")">Profil Düzenle</a></li>
                        <li><a href="@Url.Action("DeleteUye","Uye")">Profil Sil</a></li>

                    </ul>

                </li>
                <li style="        width: 30px;
        height: 30px;
        padding: 1px" class="icon-thumbnail fab fa-facebook-f">   </li>
                <li style="width:30px; height:30px; padding:1px" class="icon-thumbnail fab fa-twitter">   </li>
                <li style="width:30px; height:30px; padding:1px" class="icon-thumbnail fab fa-google">    </li>
                <li style="width:30px; height:30px; padding:1px" class="icon-thumbnail fab fa-linkedin">    </li>
                <li style="width:30px; height:30px; padding:1px" class="icon-thumbnail fab fa-youtube">    </li>
                <li style="width:30px; height:30px; padding:1px" class="icon-thumbnail fab fa-instagram">      </li>



                @*<li><a href="#">Drop Down 3</a></li>
        <li><a href="#">Drop Down 4</a></li>
        <li><a href="#">Drop Down 5</a></li>*@
            </ul>

        </nav><!-- #nav-menu-container -->
       

        <div style="padding:0; margin-top:80px; font-family:fantasy; color:#01579B; height:250px; width:250px; position:absolute; left:10px ">
            <aside>
                <hr style="width:200px; position:absolute; left:10px; " />
                <div class="col-1" style="width:200px;">
                    <button class="btn btn-outline-info" style="width :inherit;" type="button" onclick="location.href='@Url.Action("IndexAdmin","Admin")'">Anasayfa</button>
                    <hr style="width:200px; position:absolute; left:10px; " />
                </div>

                <div class="col-1" style="width:200px;">
                    <button class="btn btn-info" style="width:inherit;" type="button" onclick="location.href='@Url.Action("IndexKitap","Kitap")'">Tüm kitaplar</button>
                </div>
                <hr style="width:200px; position:absolute; left:10px; " />
                <div class="col-1" style="width:200px;">
                    <button class="btn btn-outline-info" style="width:inherit;" type="button" onclick="location.href='@Url.Action("IndexYazar","Yazar")'">Tüm Yazarlar</button>
                </div>
                <hr style="width:200px; position:absolute; left:10px; " />
                <div class="col-1" style="width:200px;">
                    <button class="btn btn-info" style="width:inherit;" type="button" onclick="location.href='@Url.Action("IndexAdmin","Admin")'">Tüm Üyeler</button>
                </div>
                <hr style="width:200px; position:absolute; left:10px; " />
                <div class="col-1" style="width:200px;">
                    <button class="btn btn-outline-info" style="width:inherit;" type="button" onclick="location.href='@Url.Action("KitapAra","Security")'">Kitap-Yazar Ara</button>
                </div>


            </aside>
        </div>
    </div>


</header>

KutuphaneCoresuz/Views/Shared/_HeaderUye.cshtml
        <header id="header">
            <div class="container">

                <div id="logo" class="pull-left">
                    <div id="logo" class="pull-left" style="position:absolute; top:5px; left:10px;">
                        @*@if (Context.Session["KullaniciAdi"].ToString() != null)
                        {
                            <h2 style="color:#10707f; ">Hoşgeldiniz Context.Session["KullaniciAdi"].ToString()  </h2>
                        }
                        else
                        {
                            <script type="text/javascript">
                                alert("Oturum süreniz doldu yönlendirliyorsunuz");
                                setTimeout(function () {
                                    window.location.assign("/Security/Login");
                                    //3 saniye sonra yönlenecek
                                }, 3000);
                            </script>
                        }*@
                    </div>
                </div>

                @*@if(ViewContext.RouteData.Values["controller"].ToString()=="UyeAnaSayfasi")
        {

        }*@

                <nav id="nav-menu-container">
                    <ul class="nav-menu">
                        <li>@Html.ActionLink("Anasayfa", "UyeAnaSayfasi", "Security", new { area = "" }, new { @class = "navbar-brand" })</li>

                        <li>@Html.ActionLink("Giriş Sayfası", "Login", "Security", new { area = "" }, new { @class = "navbar-brand" })</li>
                        <li>@Html.ActionLink("Kaydol", "CreateUye", "Uye", new { area = "" }, new { @class = "navbar-brand" })</li>
                        <li>@Html.ActionLink("İletişim", "", "", new { area = "" }, new { @class = "navbar-brand" })</li>
                        <li class="menu-has-children">
                            @Html.ActionLink("Profil", "UyeAnaSayfasi", "Security")
                            <ul>
                                <li><a href="#"></a></li>
                                <li><a href=@Url.Action("DetailsUye","Uye")>Profil Görüntüle</a></li>
                                <li><a href="@Url.Action("EditUye","Uye")">Profil Düzenle</a></li>
                                <li><a href="@Url.Action("DeleteUye","Uye")">Profil Sil</a></li>

                            </ul>

                        </li>
                        <li class="menu-has-children">
                            @Html.ActionLink("Kütüphane", "UyeAnaSayfasi", "Security")
                            <ul>
                                <li><a href="#"></a></li>
                                <li><a href="@Url.Action("IndexYazar","Yazar")">Tüm Yazarlar</a></li>
                                <li><a href="@Url.Action("IndexKitap","Kitap")">Tüm Kitaplar</a></li>
                            </ul>
                        </li>

                        <li style="width:30px; height:30px; padding:1px" class="icon-thumbnail fab fa-facebook-f">   </li>
                        <li style="width:30px; height:30px; padding:1px" class="icon-thumbnail fab fa-twitter">   </li>
                        <li style="width:30px; height:30px; padding:1px" class="icon-thumbnail fab fa-google">    </li>
                        <li style="width:30px; height:30px; padding:1px" class="icon-thumbnail fab fa-linkedin">    </li>
                        <li style="width:30px; height:30px; padding:1px" class="icon-thumbnail fab fa-youtube">    </li>
                        <li style="width:30px; height:30px; padding:1px" class="icon-thumbnail fab fa-instagram">      </li>
                        <br />
                        <br />



                        @*<li><a href="#">Drop Down 3</a></li>
                <li><a href="#">Drop Down 4</a></li>
                <li><a href="#">Drop Down 5</a></li>*@
                    </ul>

                </nav><!-- #nav-menu-container -->

                <button class="btn btn-outline-info" style="position:absolute; right:10px; top:150px;" onclick="location.href='@Url.Action("YazarAra","Security")'">Yazarlarda Arama Yap</button>
                <button class="btn btn-outline-info" style="position:absolute; right:10px; top:200px;" onclick="location.href='@Url.Action("KitapAra","Security")'">Kitaplarda Arama Yap</button>


                <div style="padding:0; margin-top:80px; font-family:fantasy; color:#01579B; height:250px; width:250px; position:absolute; left:10px ">
                    <aside>
                        <hr style="width:200px; position:absolute; left:10px; " />
                        <div class="col-1" style="width:200px;">
                            <button class="btn btn-outline-info" style="width :inherit;" type="button" onclick="location.href='@Url.Action("UyeAnasayfasi","Security")'">Anasayfa</button>
                            <hr style="width:200px; position:absolute; left:10px; " />
                        </div>

                        <div class="col-1" style="width:200px;">
                            <button class="btn btn-info" style="width:inherit;" type="button" onclick="location.href='@Url.Action("IndexKitap","Kitap")'">Tüm kitaplar</button>
                        </div>
                        <hr style="width:200px; position:absolute; left:10px; " />
                        <div class="col-1" style="width:200px;">
                            <button class="btn btn-outline-info" style="width:inherit;" type="button" onclick="location.href='@Url.Action("IndexYazar","Yazar")'">Tüm Yazarlar</button>
                        </div>
                        <hr style="width:200px; position:absolute; left:10px; " />
                        <div class="col-1" style="width:200px;">
                            <button class="btn btn-info" style="width:inherit;" type="button" onclick="location.href='@Url.Action("KitapAra","Security")'">Kitap-Yazar Ara</button>
                        </div>


                    </aside>
                </div>
            </div>
           
          
        </header>